/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ArtisanDashboardIndexImport } from './routes/artisan/dashboard/index'
import { Route as ArtisanAuthRegisterIndexImport } from './routes/artisan/auth/register/index'
import { Route as ArtisanAuthLoginIndexImport } from './routes/artisan/auth/login/index'
import { Route as ArtisanAuthForgotPasswordIndexImport } from './routes/artisan/auth/forgot-password/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanDashboardIndexRoute = ArtisanDashboardIndexImport.update({
  id: '/artisan/dashboard/',
  path: '/artisan/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanAuthRegisterIndexRoute = ArtisanAuthRegisterIndexImport.update({
  id: '/artisan/auth/register/',
  path: '/artisan/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanAuthLoginIndexRoute = ArtisanAuthLoginIndexImport.update({
  id: '/artisan/auth/login/',
  path: '/artisan/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanAuthForgotPasswordIndexRoute =
  ArtisanAuthForgotPasswordIndexImport.update({
    id: '/artisan/auth/forgot-password/',
    path: '/artisan/auth/forgot-password/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/': {
      id: '/artisan/dashboard/'
      path: '/artisan/dashboard'
      fullPath: '/artisan/dashboard'
      preLoaderRoute: typeof ArtisanDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/forgot-password/': {
      id: '/artisan/auth/forgot-password/'
      path: '/artisan/auth/forgot-password'
      fullPath: '/artisan/auth/forgot-password'
      preLoaderRoute: typeof ArtisanAuthForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/login/': {
      id: '/artisan/auth/login/'
      path: '/artisan/auth/login'
      fullPath: '/artisan/auth/login'
      preLoaderRoute: typeof ArtisanAuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/register/': {
      id: '/artisan/auth/register/'
      path: '/artisan/auth/register'
      fullPath: '/artisan/auth/register'
      preLoaderRoute: typeof ArtisanAuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artisan/dashboard': typeof ArtisanDashboardIndexRoute
  '/artisan/auth/forgot-password': typeof ArtisanAuthForgotPasswordIndexRoute
  '/artisan/auth/login': typeof ArtisanAuthLoginIndexRoute
  '/artisan/auth/register': typeof ArtisanAuthRegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artisan/dashboard': typeof ArtisanDashboardIndexRoute
  '/artisan/auth/forgot-password': typeof ArtisanAuthForgotPasswordIndexRoute
  '/artisan/auth/login': typeof ArtisanAuthLoginIndexRoute
  '/artisan/auth/register': typeof ArtisanAuthRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/artisan/dashboard/': typeof ArtisanDashboardIndexRoute
  '/artisan/auth/forgot-password/': typeof ArtisanAuthForgotPasswordIndexRoute
  '/artisan/auth/login/': typeof ArtisanAuthLoginIndexRoute
  '/artisan/auth/register/': typeof ArtisanAuthRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artisan/dashboard'
    | '/artisan/auth/forgot-password'
    | '/artisan/auth/login'
    | '/artisan/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artisan/dashboard'
    | '/artisan/auth/forgot-password'
    | '/artisan/auth/login'
    | '/artisan/auth/register'
  id:
    | '__root__'
    | '/'
    | '/artisan/dashboard/'
    | '/artisan/auth/forgot-password/'
    | '/artisan/auth/login/'
    | '/artisan/auth/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtisanDashboardIndexRoute: typeof ArtisanDashboardIndexRoute
  ArtisanAuthForgotPasswordIndexRoute: typeof ArtisanAuthForgotPasswordIndexRoute
  ArtisanAuthLoginIndexRoute: typeof ArtisanAuthLoginIndexRoute
  ArtisanAuthRegisterIndexRoute: typeof ArtisanAuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtisanDashboardIndexRoute: ArtisanDashboardIndexRoute,
  ArtisanAuthForgotPasswordIndexRoute: ArtisanAuthForgotPasswordIndexRoute,
  ArtisanAuthLoginIndexRoute: ArtisanAuthLoginIndexRoute,
  ArtisanAuthRegisterIndexRoute: ArtisanAuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/artisan/dashboard/",
        "/artisan/auth/forgot-password/",
        "/artisan/auth/login/",
        "/artisan/auth/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/artisan/dashboard/": {
      "filePath": "artisan/dashboard/index.tsx"
    },
    "/artisan/auth/forgot-password/": {
      "filePath": "artisan/auth/forgot-password/index.tsx"
    },
    "/artisan/auth/login/": {
      "filePath": "artisan/auth/login/index.tsx"
    },
    "/artisan/auth/register/": {
      "filePath": "artisan/auth/register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
