/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ArtisanDashboardIndexImport } from './routes/artisan/dashboard/index'
import { Route as ClientAuthRegisterIndexImport } from './routes/client/auth/register/index'
import { Route as ArtisanAuthLoginIndexImport } from './routes/artisan/auth/login/index'
import { Route as ArtisanAuthForgotPasswordIndexImport } from './routes/artisan/auth/forgot-password/index'
import { Route as ArtisanDashboardDashboardPagesScheduleImport } from './routes/artisan/dashboard/dashboard-pages/Schedule'
import { Route as ArtisanDashboardDashboardPagesProfileModalImport } from './routes/artisan/dashboard/dashboard-pages/ProfileModal'
import { Route as ArtisanDashboardDashboardPagesOrdersImport } from './routes/artisan/dashboard/dashboard-pages/Orders'
import { Route as ArtisanDashboardDashboardPagesMessagesImport } from './routes/artisan/dashboard/dashboard-pages/Messages'
import { Route as ArtisanDashboardDashboardPagesFindProProfileViewImport } from './routes/artisan/dashboard/dashboard-pages/FindProProfileView'
import { Route as ArtisanDashboardDashboardPagesFindProHeaderImport } from './routes/artisan/dashboard/dashboard-pages/FindProHeader'
import { Route as ArtisanDashboardDashboardPagesFavoriteImport } from './routes/artisan/dashboard/dashboard-pages/Favorite'
import { Route as ArtisanDashboardDashboardPagesDmapImport } from './routes/artisan/dashboard/dashboard-pages/Dmap'
import { Route as ArtisanDashboardDashboardPagesDashboardPageImport } from './routes/artisan/dashboard/dashboard-pages/DashboardPage'
import { Route as ArtisanDashboardDashBoardComponentTestsImport } from './routes/artisan/dashboard/DashBoardComponent/tests'
import { Route as ArtisanDashboardDashBoardComponentViewScheduleImport } from './routes/artisan/dashboard/DashBoardComponent/ViewSchedule'
import { Route as ArtisanDashboardDashBoardComponentStarRatingImport } from './routes/artisan/dashboard/DashBoardComponent/StarRating'
import { Route as ArtisanDashboardDashBoardComponentSideBarNavImport } from './routes/artisan/dashboard/DashBoardComponent/SideBarNav'
import { Route as ArtisanDashboardDashBoardComponentProfileDetailsImport } from './routes/artisan/dashboard/DashBoardComponent/ProfileDetails'
import { Route as ArtisanDashboardDashBoardComponentProfileButtonImport } from './routes/artisan/dashboard/DashBoardComponent/ProfileButton'
import { Route as ArtisanDashboardDashBoardComponentNotificationDetailsImport } from './routes/artisan/dashboard/DashBoardComponent/NotificationDetails'
import { Route as ArtisanDashboardDashBoardComponentNotificationImport } from './routes/artisan/dashboard/DashBoardComponent/Notification'
import { Route as ArtisanDashboardDashBoardComponentFindProReviewsImport } from './routes/artisan/dashboard/DashBoardComponent/FindProReviews'
import { Route as ArtisanDashboardDashBoardComponentFindProProfileSchedulesImport } from './routes/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
import { Route as ArtisanDashboardDashBoardComponentFindProProfileOverviewImport } from './routes/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
import { Route as ArtisanDashboardDashBoardComponentFindProProfileDetailImport } from './routes/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
import { Route as ArtisanDashboardDashBoardComponentFindProAllStatusImport } from './routes/artisan/dashboard/DashBoardComponent/FindProAllStatus'
import { Route as ArtisanDashboardDashBoardComponentFindProAllKindsImport } from './routes/artisan/dashboard/DashBoardComponent/FindProAllKinds'
import { Route as ArtisanDashboardDashBoardComponentFindProAllDistancesImport } from './routes/artisan/dashboard/DashBoardComponent/FindProAllDistances'
import { Route as ArtisanDashboardDashBoardComponentFindProAllCitiesImport } from './routes/artisan/dashboard/DashBoardComponent/FindProAllCities'
import { Route as ArtisanDashboardDashBoardComponentDashboardMainPageImport } from './routes/artisan/dashboard/DashBoardComponent/DashboardMainPage'
import { Route as ArtisanDashboardDashBoardComponentDashboarFeaturesImport } from './routes/artisan/dashboard/DashBoardComponent/DashboarFeatures'
import { Route as ArtisanDashboardDashBoardComponentDashBoardMapImport } from './routes/artisan/dashboard/DashBoardComponent/DashBoardMap'
import { Route as ArtisanAuthRegisterVerificationCodeImport } from './routes/artisan/auth/register/VerificationCode'
import { Route as ArtisanAuthRegisterClientImport } from './routes/artisan/auth/register/Client'
import { Route as ArtisanAuthRegisterArtisantImport } from './routes/artisan/auth/register/Artisant'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanDashboardIndexRoute = ArtisanDashboardIndexImport.update({
  id: '/artisan/dashboard/',
  path: '/artisan/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ClientAuthRegisterIndexRoute = ClientAuthRegisterIndexImport.update({
  id: '/client/auth/register/',
  path: '/client/auth/register/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanAuthLoginIndexRoute = ArtisanAuthLoginIndexImport.update({
  id: '/artisan/auth/login/',
  path: '/artisan/auth/login/',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanAuthForgotPasswordIndexRoute =
  ArtisanAuthForgotPasswordIndexImport.update({
    id: '/artisan/auth/forgot-password/',
    path: '/artisan/auth/forgot-password/',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesScheduleRoute =
  ArtisanDashboardDashboardPagesScheduleImport.update({
    id: '/artisan/dashboard/dashboard-pages/Schedule',
    path: '/artisan/dashboard/dashboard-pages/Schedule',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesProfileModalRoute =
  ArtisanDashboardDashboardPagesProfileModalImport.update({
    id: '/artisan/dashboard/dashboard-pages/ProfileModal',
    path: '/artisan/dashboard/dashboard-pages/ProfileModal',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesOrdersRoute =
  ArtisanDashboardDashboardPagesOrdersImport.update({
    id: '/artisan/dashboard/dashboard-pages/Orders',
    path: '/artisan/dashboard/dashboard-pages/Orders',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesMessagesRoute =
  ArtisanDashboardDashboardPagesMessagesImport.update({
    id: '/artisan/dashboard/dashboard-pages/Messages',
    path: '/artisan/dashboard/dashboard-pages/Messages',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesFindProProfileViewRoute =
  ArtisanDashboardDashboardPagesFindProProfileViewImport.update({
    id: '/artisan/dashboard/dashboard-pages/FindProProfileView',
    path: '/artisan/dashboard/dashboard-pages/FindProProfileView',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesFindProHeaderRoute =
  ArtisanDashboardDashboardPagesFindProHeaderImport.update({
    id: '/artisan/dashboard/dashboard-pages/FindProHeader',
    path: '/artisan/dashboard/dashboard-pages/FindProHeader',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesFavoriteRoute =
  ArtisanDashboardDashboardPagesFavoriteImport.update({
    id: '/artisan/dashboard/dashboard-pages/Favorite',
    path: '/artisan/dashboard/dashboard-pages/Favorite',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesDmapRoute =
  ArtisanDashboardDashboardPagesDmapImport.update({
    id: '/artisan/dashboard/dashboard-pages/Dmap',
    path: '/artisan/dashboard/dashboard-pages/Dmap',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashboardPagesDashboardPageRoute =
  ArtisanDashboardDashboardPagesDashboardPageImport.update({
    id: '/artisan/dashboard/dashboard-pages/DashboardPage',
    path: '/artisan/dashboard/dashboard-pages/DashboardPage',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentTestsRoute =
  ArtisanDashboardDashBoardComponentTestsImport.update({
    id: '/artisan/dashboard/DashBoardComponent/tests',
    path: '/artisan/dashboard/DashBoardComponent/tests',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentViewScheduleRoute =
  ArtisanDashboardDashBoardComponentViewScheduleImport.update({
    id: '/artisan/dashboard/DashBoardComponent/ViewSchedule',
    path: '/artisan/dashboard/DashBoardComponent/ViewSchedule',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentStarRatingRoute =
  ArtisanDashboardDashBoardComponentStarRatingImport.update({
    id: '/artisan/dashboard/DashBoardComponent/StarRating',
    path: '/artisan/dashboard/DashBoardComponent/StarRating',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentSideBarNavRoute =
  ArtisanDashboardDashBoardComponentSideBarNavImport.update({
    id: '/artisan/dashboard/DashBoardComponent/SideBarNav',
    path: '/artisan/dashboard/DashBoardComponent/SideBarNav',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentProfileDetailsRoute =
  ArtisanDashboardDashBoardComponentProfileDetailsImport.update({
    id: '/artisan/dashboard/DashBoardComponent/ProfileDetails',
    path: '/artisan/dashboard/DashBoardComponent/ProfileDetails',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentProfileButtonRoute =
  ArtisanDashboardDashBoardComponentProfileButtonImport.update({
    id: '/artisan/dashboard/DashBoardComponent/ProfileButton',
    path: '/artisan/dashboard/DashBoardComponent/ProfileButton',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentNotificationDetailsRoute =
  ArtisanDashboardDashBoardComponentNotificationDetailsImport.update({
    id: '/artisan/dashboard/DashBoardComponent/NotificationDetails',
    path: '/artisan/dashboard/DashBoardComponent/NotificationDetails',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentNotificationRoute =
  ArtisanDashboardDashBoardComponentNotificationImport.update({
    id: '/artisan/dashboard/DashBoardComponent/Notification',
    path: '/artisan/dashboard/DashBoardComponent/Notification',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProReviewsRoute =
  ArtisanDashboardDashBoardComponentFindProReviewsImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProReviews',
    path: '/artisan/dashboard/DashBoardComponent/FindProReviews',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute =
  ArtisanDashboardDashBoardComponentFindProProfileSchedulesImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules',
    path: '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute =
  ArtisanDashboardDashBoardComponentFindProProfileOverviewImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProProfileOverview',
    path: '/artisan/dashboard/DashBoardComponent/FindProProfileOverview',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProProfileDetailRoute =
  ArtisanDashboardDashBoardComponentFindProProfileDetailImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProProfileDetail',
    path: '/artisan/dashboard/DashBoardComponent/FindProProfileDetail',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProAllStatusRoute =
  ArtisanDashboardDashBoardComponentFindProAllStatusImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProAllStatus',
    path: '/artisan/dashboard/DashBoardComponent/FindProAllStatus',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProAllKindsRoute =
  ArtisanDashboardDashBoardComponentFindProAllKindsImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProAllKinds',
    path: '/artisan/dashboard/DashBoardComponent/FindProAllKinds',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProAllDistancesRoute =
  ArtisanDashboardDashBoardComponentFindProAllDistancesImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProAllDistances',
    path: '/artisan/dashboard/DashBoardComponent/FindProAllDistances',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentFindProAllCitiesRoute =
  ArtisanDashboardDashBoardComponentFindProAllCitiesImport.update({
    id: '/artisan/dashboard/DashBoardComponent/FindProAllCities',
    path: '/artisan/dashboard/DashBoardComponent/FindProAllCities',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentDashboardMainPageRoute =
  ArtisanDashboardDashBoardComponentDashboardMainPageImport.update({
    id: '/artisan/dashboard/DashBoardComponent/DashboardMainPage',
    path: '/artisan/dashboard/DashBoardComponent/DashboardMainPage',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentDashboarFeaturesRoute =
  ArtisanDashboardDashBoardComponentDashboarFeaturesImport.update({
    id: '/artisan/dashboard/DashBoardComponent/DashboarFeatures',
    path: '/artisan/dashboard/DashBoardComponent/DashboarFeatures',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanDashboardDashBoardComponentDashBoardMapRoute =
  ArtisanDashboardDashBoardComponentDashBoardMapImport.update({
    id: '/artisan/dashboard/DashBoardComponent/DashBoardMap',
    path: '/artisan/dashboard/DashBoardComponent/DashBoardMap',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanAuthRegisterVerificationCodeRoute =
  ArtisanAuthRegisterVerificationCodeImport.update({
    id: '/artisan/auth/register/VerificationCode',
    path: '/artisan/auth/register/VerificationCode',
    getParentRoute: () => rootRoute,
  } as any)

const ArtisanAuthRegisterClientRoute = ArtisanAuthRegisterClientImport.update({
  id: '/artisan/auth/register/Client',
  path: '/artisan/auth/register/Client',
  getParentRoute: () => rootRoute,
} as any)

const ArtisanAuthRegisterArtisantRoute =
  ArtisanAuthRegisterArtisantImport.update({
    id: '/artisan/auth/register/Artisant',
    path: '/artisan/auth/register/Artisant',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/': {
      id: '/artisan/dashboard/'
      path: '/artisan/dashboard'
      fullPath: '/artisan/dashboard'
      preLoaderRoute: typeof ArtisanDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/register/Artisant': {
      id: '/artisan/auth/register/Artisant'
      path: '/artisan/auth/register/Artisant'
      fullPath: '/artisan/auth/register/Artisant'
      preLoaderRoute: typeof ArtisanAuthRegisterArtisantImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/register/Client': {
      id: '/artisan/auth/register/Client'
      path: '/artisan/auth/register/Client'
      fullPath: '/artisan/auth/register/Client'
      preLoaderRoute: typeof ArtisanAuthRegisterClientImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/register/VerificationCode': {
      id: '/artisan/auth/register/VerificationCode'
      path: '/artisan/auth/register/VerificationCode'
      fullPath: '/artisan/auth/register/VerificationCode'
      preLoaderRoute: typeof ArtisanAuthRegisterVerificationCodeImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/DashBoardMap': {
      id: '/artisan/dashboard/DashBoardComponent/DashBoardMap'
      path: '/artisan/dashboard/DashBoardComponent/DashBoardMap'
      fullPath: '/artisan/dashboard/DashBoardComponent/DashBoardMap'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentDashBoardMapImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/DashboarFeatures': {
      id: '/artisan/dashboard/DashBoardComponent/DashboarFeatures'
      path: '/artisan/dashboard/DashBoardComponent/DashboarFeatures'
      fullPath: '/artisan/dashboard/DashBoardComponent/DashboarFeatures'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentDashboarFeaturesImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/DashboardMainPage': {
      id: '/artisan/dashboard/DashBoardComponent/DashboardMainPage'
      path: '/artisan/dashboard/DashBoardComponent/DashboardMainPage'
      fullPath: '/artisan/dashboard/DashBoardComponent/DashboardMainPage'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentDashboardMainPageImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProAllCities': {
      id: '/artisan/dashboard/DashBoardComponent/FindProAllCities'
      path: '/artisan/dashboard/DashBoardComponent/FindProAllCities'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProAllCities'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProAllCitiesImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProAllDistances': {
      id: '/artisan/dashboard/DashBoardComponent/FindProAllDistances'
      path: '/artisan/dashboard/DashBoardComponent/FindProAllDistances'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProAllDistances'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProAllDistancesImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProAllKinds': {
      id: '/artisan/dashboard/DashBoardComponent/FindProAllKinds'
      path: '/artisan/dashboard/DashBoardComponent/FindProAllKinds'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProAllKinds'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProAllKindsImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProAllStatus': {
      id: '/artisan/dashboard/DashBoardComponent/FindProAllStatus'
      path: '/artisan/dashboard/DashBoardComponent/FindProAllStatus'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProAllStatus'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProAllStatusImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProProfileDetail': {
      id: '/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
      path: '/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProProfileDetailImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProProfileOverview': {
      id: '/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
      path: '/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProProfileOverviewImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules': {
      id: '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
      path: '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProProfileSchedulesImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/FindProReviews': {
      id: '/artisan/dashboard/DashBoardComponent/FindProReviews'
      path: '/artisan/dashboard/DashBoardComponent/FindProReviews'
      fullPath: '/artisan/dashboard/DashBoardComponent/FindProReviews'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentFindProReviewsImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/Notification': {
      id: '/artisan/dashboard/DashBoardComponent/Notification'
      path: '/artisan/dashboard/DashBoardComponent/Notification'
      fullPath: '/artisan/dashboard/DashBoardComponent/Notification'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentNotificationImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/NotificationDetails': {
      id: '/artisan/dashboard/DashBoardComponent/NotificationDetails'
      path: '/artisan/dashboard/DashBoardComponent/NotificationDetails'
      fullPath: '/artisan/dashboard/DashBoardComponent/NotificationDetails'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentNotificationDetailsImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/ProfileButton': {
      id: '/artisan/dashboard/DashBoardComponent/ProfileButton'
      path: '/artisan/dashboard/DashBoardComponent/ProfileButton'
      fullPath: '/artisan/dashboard/DashBoardComponent/ProfileButton'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentProfileButtonImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/ProfileDetails': {
      id: '/artisan/dashboard/DashBoardComponent/ProfileDetails'
      path: '/artisan/dashboard/DashBoardComponent/ProfileDetails'
      fullPath: '/artisan/dashboard/DashBoardComponent/ProfileDetails'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentProfileDetailsImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/SideBarNav': {
      id: '/artisan/dashboard/DashBoardComponent/SideBarNav'
      path: '/artisan/dashboard/DashBoardComponent/SideBarNav'
      fullPath: '/artisan/dashboard/DashBoardComponent/SideBarNav'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentSideBarNavImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/StarRating': {
      id: '/artisan/dashboard/DashBoardComponent/StarRating'
      path: '/artisan/dashboard/DashBoardComponent/StarRating'
      fullPath: '/artisan/dashboard/DashBoardComponent/StarRating'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentStarRatingImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/ViewSchedule': {
      id: '/artisan/dashboard/DashBoardComponent/ViewSchedule'
      path: '/artisan/dashboard/DashBoardComponent/ViewSchedule'
      fullPath: '/artisan/dashboard/DashBoardComponent/ViewSchedule'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentViewScheduleImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/DashBoardComponent/tests': {
      id: '/artisan/dashboard/DashBoardComponent/tests'
      path: '/artisan/dashboard/DashBoardComponent/tests'
      fullPath: '/artisan/dashboard/DashBoardComponent/tests'
      preLoaderRoute: typeof ArtisanDashboardDashBoardComponentTestsImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/DashboardPage': {
      id: '/artisan/dashboard/dashboard-pages/DashboardPage'
      path: '/artisan/dashboard/dashboard-pages/DashboardPage'
      fullPath: '/artisan/dashboard/dashboard-pages/DashboardPage'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesDashboardPageImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/Dmap': {
      id: '/artisan/dashboard/dashboard-pages/Dmap'
      path: '/artisan/dashboard/dashboard-pages/Dmap'
      fullPath: '/artisan/dashboard/dashboard-pages/Dmap'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesDmapImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/Favorite': {
      id: '/artisan/dashboard/dashboard-pages/Favorite'
      path: '/artisan/dashboard/dashboard-pages/Favorite'
      fullPath: '/artisan/dashboard/dashboard-pages/Favorite'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesFavoriteImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/FindProHeader': {
      id: '/artisan/dashboard/dashboard-pages/FindProHeader'
      path: '/artisan/dashboard/dashboard-pages/FindProHeader'
      fullPath: '/artisan/dashboard/dashboard-pages/FindProHeader'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesFindProHeaderImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/FindProProfileView': {
      id: '/artisan/dashboard/dashboard-pages/FindProProfileView'
      path: '/artisan/dashboard/dashboard-pages/FindProProfileView'
      fullPath: '/artisan/dashboard/dashboard-pages/FindProProfileView'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesFindProProfileViewImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/Messages': {
      id: '/artisan/dashboard/dashboard-pages/Messages'
      path: '/artisan/dashboard/dashboard-pages/Messages'
      fullPath: '/artisan/dashboard/dashboard-pages/Messages'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesMessagesImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/Orders': {
      id: '/artisan/dashboard/dashboard-pages/Orders'
      path: '/artisan/dashboard/dashboard-pages/Orders'
      fullPath: '/artisan/dashboard/dashboard-pages/Orders'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesOrdersImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/ProfileModal': {
      id: '/artisan/dashboard/dashboard-pages/ProfileModal'
      path: '/artisan/dashboard/dashboard-pages/ProfileModal'
      fullPath: '/artisan/dashboard/dashboard-pages/ProfileModal'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesProfileModalImport
      parentRoute: typeof rootRoute
    }
    '/artisan/dashboard/dashboard-pages/Schedule': {
      id: '/artisan/dashboard/dashboard-pages/Schedule'
      path: '/artisan/dashboard/dashboard-pages/Schedule'
      fullPath: '/artisan/dashboard/dashboard-pages/Schedule'
      preLoaderRoute: typeof ArtisanDashboardDashboardPagesScheduleImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/forgot-password/': {
      id: '/artisan/auth/forgot-password/'
      path: '/artisan/auth/forgot-password'
      fullPath: '/artisan/auth/forgot-password'
      preLoaderRoute: typeof ArtisanAuthForgotPasswordIndexImport
      parentRoute: typeof rootRoute
    }
    '/artisan/auth/login/': {
      id: '/artisan/auth/login/'
      path: '/artisan/auth/login'
      fullPath: '/artisan/auth/login'
      preLoaderRoute: typeof ArtisanAuthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/client/auth/register/': {
      id: '/client/auth/register/'
      path: '/client/auth/register'
      fullPath: '/client/auth/register'
      preLoaderRoute: typeof ClientAuthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artisan/dashboard': typeof ArtisanDashboardIndexRoute
  '/artisan/auth/register/Artisant': typeof ArtisanAuthRegisterArtisantRoute
  '/artisan/auth/register/Client': typeof ArtisanAuthRegisterClientRoute
  '/artisan/auth/register/VerificationCode': typeof ArtisanAuthRegisterVerificationCodeRoute
  '/artisan/dashboard/DashBoardComponent/DashBoardMap': typeof ArtisanDashboardDashBoardComponentDashBoardMapRoute
  '/artisan/dashboard/DashBoardComponent/DashboarFeatures': typeof ArtisanDashboardDashBoardComponentDashboarFeaturesRoute
  '/artisan/dashboard/DashBoardComponent/DashboardMainPage': typeof ArtisanDashboardDashBoardComponentDashboardMainPageRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllCities': typeof ArtisanDashboardDashBoardComponentFindProAllCitiesRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllDistances': typeof ArtisanDashboardDashBoardComponentFindProAllDistancesRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllKinds': typeof ArtisanDashboardDashBoardComponentFindProAllKindsRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllStatus': typeof ArtisanDashboardDashBoardComponentFindProAllStatusRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileDetail': typeof ArtisanDashboardDashBoardComponentFindProProfileDetailRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileOverview': typeof ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules': typeof ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute
  '/artisan/dashboard/DashBoardComponent/FindProReviews': typeof ArtisanDashboardDashBoardComponentFindProReviewsRoute
  '/artisan/dashboard/DashBoardComponent/Notification': typeof ArtisanDashboardDashBoardComponentNotificationRoute
  '/artisan/dashboard/DashBoardComponent/NotificationDetails': typeof ArtisanDashboardDashBoardComponentNotificationDetailsRoute
  '/artisan/dashboard/DashBoardComponent/ProfileButton': typeof ArtisanDashboardDashBoardComponentProfileButtonRoute
  '/artisan/dashboard/DashBoardComponent/ProfileDetails': typeof ArtisanDashboardDashBoardComponentProfileDetailsRoute
  '/artisan/dashboard/DashBoardComponent/SideBarNav': typeof ArtisanDashboardDashBoardComponentSideBarNavRoute
  '/artisan/dashboard/DashBoardComponent/StarRating': typeof ArtisanDashboardDashBoardComponentStarRatingRoute
  '/artisan/dashboard/DashBoardComponent/ViewSchedule': typeof ArtisanDashboardDashBoardComponentViewScheduleRoute
  '/artisan/dashboard/DashBoardComponent/tests': typeof ArtisanDashboardDashBoardComponentTestsRoute
  '/artisan/dashboard/dashboard-pages/DashboardPage': typeof ArtisanDashboardDashboardPagesDashboardPageRoute
  '/artisan/dashboard/dashboard-pages/Dmap': typeof ArtisanDashboardDashboardPagesDmapRoute
  '/artisan/dashboard/dashboard-pages/Favorite': typeof ArtisanDashboardDashboardPagesFavoriteRoute
  '/artisan/dashboard/dashboard-pages/FindProHeader': typeof ArtisanDashboardDashboardPagesFindProHeaderRoute
  '/artisan/dashboard/dashboard-pages/FindProProfileView': typeof ArtisanDashboardDashboardPagesFindProProfileViewRoute
  '/artisan/dashboard/dashboard-pages/Messages': typeof ArtisanDashboardDashboardPagesMessagesRoute
  '/artisan/dashboard/dashboard-pages/Orders': typeof ArtisanDashboardDashboardPagesOrdersRoute
  '/artisan/dashboard/dashboard-pages/ProfileModal': typeof ArtisanDashboardDashboardPagesProfileModalRoute
  '/artisan/dashboard/dashboard-pages/Schedule': typeof ArtisanDashboardDashboardPagesScheduleRoute
  '/artisan/auth/forgot-password': typeof ArtisanAuthForgotPasswordIndexRoute
  '/artisan/auth/login': typeof ArtisanAuthLoginIndexRoute
  '/client/auth/register': typeof ClientAuthRegisterIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artisan/dashboard': typeof ArtisanDashboardIndexRoute
  '/artisan/auth/register/Artisant': typeof ArtisanAuthRegisterArtisantRoute
  '/artisan/auth/register/Client': typeof ArtisanAuthRegisterClientRoute
  '/artisan/auth/register/VerificationCode': typeof ArtisanAuthRegisterVerificationCodeRoute
  '/artisan/dashboard/DashBoardComponent/DashBoardMap': typeof ArtisanDashboardDashBoardComponentDashBoardMapRoute
  '/artisan/dashboard/DashBoardComponent/DashboarFeatures': typeof ArtisanDashboardDashBoardComponentDashboarFeaturesRoute
  '/artisan/dashboard/DashBoardComponent/DashboardMainPage': typeof ArtisanDashboardDashBoardComponentDashboardMainPageRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllCities': typeof ArtisanDashboardDashBoardComponentFindProAllCitiesRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllDistances': typeof ArtisanDashboardDashBoardComponentFindProAllDistancesRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllKinds': typeof ArtisanDashboardDashBoardComponentFindProAllKindsRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllStatus': typeof ArtisanDashboardDashBoardComponentFindProAllStatusRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileDetail': typeof ArtisanDashboardDashBoardComponentFindProProfileDetailRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileOverview': typeof ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules': typeof ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute
  '/artisan/dashboard/DashBoardComponent/FindProReviews': typeof ArtisanDashboardDashBoardComponentFindProReviewsRoute
  '/artisan/dashboard/DashBoardComponent/Notification': typeof ArtisanDashboardDashBoardComponentNotificationRoute
  '/artisan/dashboard/DashBoardComponent/NotificationDetails': typeof ArtisanDashboardDashBoardComponentNotificationDetailsRoute
  '/artisan/dashboard/DashBoardComponent/ProfileButton': typeof ArtisanDashboardDashBoardComponentProfileButtonRoute
  '/artisan/dashboard/DashBoardComponent/ProfileDetails': typeof ArtisanDashboardDashBoardComponentProfileDetailsRoute
  '/artisan/dashboard/DashBoardComponent/SideBarNav': typeof ArtisanDashboardDashBoardComponentSideBarNavRoute
  '/artisan/dashboard/DashBoardComponent/StarRating': typeof ArtisanDashboardDashBoardComponentStarRatingRoute
  '/artisan/dashboard/DashBoardComponent/ViewSchedule': typeof ArtisanDashboardDashBoardComponentViewScheduleRoute
  '/artisan/dashboard/DashBoardComponent/tests': typeof ArtisanDashboardDashBoardComponentTestsRoute
  '/artisan/dashboard/dashboard-pages/DashboardPage': typeof ArtisanDashboardDashboardPagesDashboardPageRoute
  '/artisan/dashboard/dashboard-pages/Dmap': typeof ArtisanDashboardDashboardPagesDmapRoute
  '/artisan/dashboard/dashboard-pages/Favorite': typeof ArtisanDashboardDashboardPagesFavoriteRoute
  '/artisan/dashboard/dashboard-pages/FindProHeader': typeof ArtisanDashboardDashboardPagesFindProHeaderRoute
  '/artisan/dashboard/dashboard-pages/FindProProfileView': typeof ArtisanDashboardDashboardPagesFindProProfileViewRoute
  '/artisan/dashboard/dashboard-pages/Messages': typeof ArtisanDashboardDashboardPagesMessagesRoute
  '/artisan/dashboard/dashboard-pages/Orders': typeof ArtisanDashboardDashboardPagesOrdersRoute
  '/artisan/dashboard/dashboard-pages/ProfileModal': typeof ArtisanDashboardDashboardPagesProfileModalRoute
  '/artisan/dashboard/dashboard-pages/Schedule': typeof ArtisanDashboardDashboardPagesScheduleRoute
  '/artisan/auth/forgot-password': typeof ArtisanAuthForgotPasswordIndexRoute
  '/artisan/auth/login': typeof ArtisanAuthLoginIndexRoute
  '/client/auth/register': typeof ClientAuthRegisterIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/artisan/dashboard/': typeof ArtisanDashboardIndexRoute
  '/artisan/auth/register/Artisant': typeof ArtisanAuthRegisterArtisantRoute
  '/artisan/auth/register/Client': typeof ArtisanAuthRegisterClientRoute
  '/artisan/auth/register/VerificationCode': typeof ArtisanAuthRegisterVerificationCodeRoute
  '/artisan/dashboard/DashBoardComponent/DashBoardMap': typeof ArtisanDashboardDashBoardComponentDashBoardMapRoute
  '/artisan/dashboard/DashBoardComponent/DashboarFeatures': typeof ArtisanDashboardDashBoardComponentDashboarFeaturesRoute
  '/artisan/dashboard/DashBoardComponent/DashboardMainPage': typeof ArtisanDashboardDashBoardComponentDashboardMainPageRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllCities': typeof ArtisanDashboardDashBoardComponentFindProAllCitiesRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllDistances': typeof ArtisanDashboardDashBoardComponentFindProAllDistancesRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllKinds': typeof ArtisanDashboardDashBoardComponentFindProAllKindsRoute
  '/artisan/dashboard/DashBoardComponent/FindProAllStatus': typeof ArtisanDashboardDashBoardComponentFindProAllStatusRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileDetail': typeof ArtisanDashboardDashBoardComponentFindProProfileDetailRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileOverview': typeof ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute
  '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules': typeof ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute
  '/artisan/dashboard/DashBoardComponent/FindProReviews': typeof ArtisanDashboardDashBoardComponentFindProReviewsRoute
  '/artisan/dashboard/DashBoardComponent/Notification': typeof ArtisanDashboardDashBoardComponentNotificationRoute
  '/artisan/dashboard/DashBoardComponent/NotificationDetails': typeof ArtisanDashboardDashBoardComponentNotificationDetailsRoute
  '/artisan/dashboard/DashBoardComponent/ProfileButton': typeof ArtisanDashboardDashBoardComponentProfileButtonRoute
  '/artisan/dashboard/DashBoardComponent/ProfileDetails': typeof ArtisanDashboardDashBoardComponentProfileDetailsRoute
  '/artisan/dashboard/DashBoardComponent/SideBarNav': typeof ArtisanDashboardDashBoardComponentSideBarNavRoute
  '/artisan/dashboard/DashBoardComponent/StarRating': typeof ArtisanDashboardDashBoardComponentStarRatingRoute
  '/artisan/dashboard/DashBoardComponent/ViewSchedule': typeof ArtisanDashboardDashBoardComponentViewScheduleRoute
  '/artisan/dashboard/DashBoardComponent/tests': typeof ArtisanDashboardDashBoardComponentTestsRoute
  '/artisan/dashboard/dashboard-pages/DashboardPage': typeof ArtisanDashboardDashboardPagesDashboardPageRoute
  '/artisan/dashboard/dashboard-pages/Dmap': typeof ArtisanDashboardDashboardPagesDmapRoute
  '/artisan/dashboard/dashboard-pages/Favorite': typeof ArtisanDashboardDashboardPagesFavoriteRoute
  '/artisan/dashboard/dashboard-pages/FindProHeader': typeof ArtisanDashboardDashboardPagesFindProHeaderRoute
  '/artisan/dashboard/dashboard-pages/FindProProfileView': typeof ArtisanDashboardDashboardPagesFindProProfileViewRoute
  '/artisan/dashboard/dashboard-pages/Messages': typeof ArtisanDashboardDashboardPagesMessagesRoute
  '/artisan/dashboard/dashboard-pages/Orders': typeof ArtisanDashboardDashboardPagesOrdersRoute
  '/artisan/dashboard/dashboard-pages/ProfileModal': typeof ArtisanDashboardDashboardPagesProfileModalRoute
  '/artisan/dashboard/dashboard-pages/Schedule': typeof ArtisanDashboardDashboardPagesScheduleRoute
  '/artisan/auth/forgot-password/': typeof ArtisanAuthForgotPasswordIndexRoute
  '/artisan/auth/login/': typeof ArtisanAuthLoginIndexRoute
  '/client/auth/register/': typeof ClientAuthRegisterIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artisan/dashboard'
    | '/artisan/auth/register/Artisant'
    | '/artisan/auth/register/Client'
    | '/artisan/auth/register/VerificationCode'
    | '/artisan/dashboard/DashBoardComponent/DashBoardMap'
    | '/artisan/dashboard/DashBoardComponent/DashboarFeatures'
    | '/artisan/dashboard/DashBoardComponent/DashboardMainPage'
    | '/artisan/dashboard/DashBoardComponent/FindProAllCities'
    | '/artisan/dashboard/DashBoardComponent/FindProAllDistances'
    | '/artisan/dashboard/DashBoardComponent/FindProAllKinds'
    | '/artisan/dashboard/DashBoardComponent/FindProAllStatus'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
    | '/artisan/dashboard/DashBoardComponent/FindProReviews'
    | '/artisan/dashboard/DashBoardComponent/Notification'
    | '/artisan/dashboard/DashBoardComponent/NotificationDetails'
    | '/artisan/dashboard/DashBoardComponent/ProfileButton'
    | '/artisan/dashboard/DashBoardComponent/ProfileDetails'
    | '/artisan/dashboard/DashBoardComponent/SideBarNav'
    | '/artisan/dashboard/DashBoardComponent/StarRating'
    | '/artisan/dashboard/DashBoardComponent/ViewSchedule'
    | '/artisan/dashboard/DashBoardComponent/tests'
    | '/artisan/dashboard/dashboard-pages/DashboardPage'
    | '/artisan/dashboard/dashboard-pages/Dmap'
    | '/artisan/dashboard/dashboard-pages/Favorite'
    | '/artisan/dashboard/dashboard-pages/FindProHeader'
    | '/artisan/dashboard/dashboard-pages/FindProProfileView'
    | '/artisan/dashboard/dashboard-pages/Messages'
    | '/artisan/dashboard/dashboard-pages/Orders'
    | '/artisan/dashboard/dashboard-pages/ProfileModal'
    | '/artisan/dashboard/dashboard-pages/Schedule'
    | '/artisan/auth/forgot-password'
    | '/artisan/auth/login'
    | '/client/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artisan/dashboard'
    | '/artisan/auth/register/Artisant'
    | '/artisan/auth/register/Client'
    | '/artisan/auth/register/VerificationCode'
    | '/artisan/dashboard/DashBoardComponent/DashBoardMap'
    | '/artisan/dashboard/DashBoardComponent/DashboarFeatures'
    | '/artisan/dashboard/DashBoardComponent/DashboardMainPage'
    | '/artisan/dashboard/DashBoardComponent/FindProAllCities'
    | '/artisan/dashboard/DashBoardComponent/FindProAllDistances'
    | '/artisan/dashboard/DashBoardComponent/FindProAllKinds'
    | '/artisan/dashboard/DashBoardComponent/FindProAllStatus'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
    | '/artisan/dashboard/DashBoardComponent/FindProReviews'
    | '/artisan/dashboard/DashBoardComponent/Notification'
    | '/artisan/dashboard/DashBoardComponent/NotificationDetails'
    | '/artisan/dashboard/DashBoardComponent/ProfileButton'
    | '/artisan/dashboard/DashBoardComponent/ProfileDetails'
    | '/artisan/dashboard/DashBoardComponent/SideBarNav'
    | '/artisan/dashboard/DashBoardComponent/StarRating'
    | '/artisan/dashboard/DashBoardComponent/ViewSchedule'
    | '/artisan/dashboard/DashBoardComponent/tests'
    | '/artisan/dashboard/dashboard-pages/DashboardPage'
    | '/artisan/dashboard/dashboard-pages/Dmap'
    | '/artisan/dashboard/dashboard-pages/Favorite'
    | '/artisan/dashboard/dashboard-pages/FindProHeader'
    | '/artisan/dashboard/dashboard-pages/FindProProfileView'
    | '/artisan/dashboard/dashboard-pages/Messages'
    | '/artisan/dashboard/dashboard-pages/Orders'
    | '/artisan/dashboard/dashboard-pages/ProfileModal'
    | '/artisan/dashboard/dashboard-pages/Schedule'
    | '/artisan/auth/forgot-password'
    | '/artisan/auth/login'
    | '/client/auth/register'
  id:
    | '__root__'
    | '/'
    | '/artisan/dashboard/'
    | '/artisan/auth/register/Artisant'
    | '/artisan/auth/register/Client'
    | '/artisan/auth/register/VerificationCode'
    | '/artisan/dashboard/DashBoardComponent/DashBoardMap'
    | '/artisan/dashboard/DashBoardComponent/DashboarFeatures'
    | '/artisan/dashboard/DashBoardComponent/DashboardMainPage'
    | '/artisan/dashboard/DashBoardComponent/FindProAllCities'
    | '/artisan/dashboard/DashBoardComponent/FindProAllDistances'
    | '/artisan/dashboard/DashBoardComponent/FindProAllKinds'
    | '/artisan/dashboard/DashBoardComponent/FindProAllStatus'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileDetail'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileOverview'
    | '/artisan/dashboard/DashBoardComponent/FindProProfileSchedules'
    | '/artisan/dashboard/DashBoardComponent/FindProReviews'
    | '/artisan/dashboard/DashBoardComponent/Notification'
    | '/artisan/dashboard/DashBoardComponent/NotificationDetails'
    | '/artisan/dashboard/DashBoardComponent/ProfileButton'
    | '/artisan/dashboard/DashBoardComponent/ProfileDetails'
    | '/artisan/dashboard/DashBoardComponent/SideBarNav'
    | '/artisan/dashboard/DashBoardComponent/StarRating'
    | '/artisan/dashboard/DashBoardComponent/ViewSchedule'
    | '/artisan/dashboard/DashBoardComponent/tests'
    | '/artisan/dashboard/dashboard-pages/DashboardPage'
    | '/artisan/dashboard/dashboard-pages/Dmap'
    | '/artisan/dashboard/dashboard-pages/Favorite'
    | '/artisan/dashboard/dashboard-pages/FindProHeader'
    | '/artisan/dashboard/dashboard-pages/FindProProfileView'
    | '/artisan/dashboard/dashboard-pages/Messages'
    | '/artisan/dashboard/dashboard-pages/Orders'
    | '/artisan/dashboard/dashboard-pages/ProfileModal'
    | '/artisan/dashboard/dashboard-pages/Schedule'
    | '/artisan/auth/forgot-password/'
    | '/artisan/auth/login/'
    | '/client/auth/register/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtisanDashboardIndexRoute: typeof ArtisanDashboardIndexRoute
  ArtisanAuthRegisterArtisantRoute: typeof ArtisanAuthRegisterArtisantRoute
  ArtisanAuthRegisterClientRoute: typeof ArtisanAuthRegisterClientRoute
  ArtisanAuthRegisterVerificationCodeRoute: typeof ArtisanAuthRegisterVerificationCodeRoute
  ArtisanDashboardDashBoardComponentDashBoardMapRoute: typeof ArtisanDashboardDashBoardComponentDashBoardMapRoute
  ArtisanDashboardDashBoardComponentDashboarFeaturesRoute: typeof ArtisanDashboardDashBoardComponentDashboarFeaturesRoute
  ArtisanDashboardDashBoardComponentDashboardMainPageRoute: typeof ArtisanDashboardDashBoardComponentDashboardMainPageRoute
  ArtisanDashboardDashBoardComponentFindProAllCitiesRoute: typeof ArtisanDashboardDashBoardComponentFindProAllCitiesRoute
  ArtisanDashboardDashBoardComponentFindProAllDistancesRoute: typeof ArtisanDashboardDashBoardComponentFindProAllDistancesRoute
  ArtisanDashboardDashBoardComponentFindProAllKindsRoute: typeof ArtisanDashboardDashBoardComponentFindProAllKindsRoute
  ArtisanDashboardDashBoardComponentFindProAllStatusRoute: typeof ArtisanDashboardDashBoardComponentFindProAllStatusRoute
  ArtisanDashboardDashBoardComponentFindProProfileDetailRoute: typeof ArtisanDashboardDashBoardComponentFindProProfileDetailRoute
  ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute: typeof ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute
  ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute: typeof ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute
  ArtisanDashboardDashBoardComponentFindProReviewsRoute: typeof ArtisanDashboardDashBoardComponentFindProReviewsRoute
  ArtisanDashboardDashBoardComponentNotificationRoute: typeof ArtisanDashboardDashBoardComponentNotificationRoute
  ArtisanDashboardDashBoardComponentNotificationDetailsRoute: typeof ArtisanDashboardDashBoardComponentNotificationDetailsRoute
  ArtisanDashboardDashBoardComponentProfileButtonRoute: typeof ArtisanDashboardDashBoardComponentProfileButtonRoute
  ArtisanDashboardDashBoardComponentProfileDetailsRoute: typeof ArtisanDashboardDashBoardComponentProfileDetailsRoute
  ArtisanDashboardDashBoardComponentSideBarNavRoute: typeof ArtisanDashboardDashBoardComponentSideBarNavRoute
  ArtisanDashboardDashBoardComponentStarRatingRoute: typeof ArtisanDashboardDashBoardComponentStarRatingRoute
  ArtisanDashboardDashBoardComponentViewScheduleRoute: typeof ArtisanDashboardDashBoardComponentViewScheduleRoute
  ArtisanDashboardDashBoardComponentTestsRoute: typeof ArtisanDashboardDashBoardComponentTestsRoute
  ArtisanDashboardDashboardPagesDashboardPageRoute: typeof ArtisanDashboardDashboardPagesDashboardPageRoute
  ArtisanDashboardDashboardPagesDmapRoute: typeof ArtisanDashboardDashboardPagesDmapRoute
  ArtisanDashboardDashboardPagesFavoriteRoute: typeof ArtisanDashboardDashboardPagesFavoriteRoute
  ArtisanDashboardDashboardPagesFindProHeaderRoute: typeof ArtisanDashboardDashboardPagesFindProHeaderRoute
  ArtisanDashboardDashboardPagesFindProProfileViewRoute: typeof ArtisanDashboardDashboardPagesFindProProfileViewRoute
  ArtisanDashboardDashboardPagesMessagesRoute: typeof ArtisanDashboardDashboardPagesMessagesRoute
  ArtisanDashboardDashboardPagesOrdersRoute: typeof ArtisanDashboardDashboardPagesOrdersRoute
  ArtisanDashboardDashboardPagesProfileModalRoute: typeof ArtisanDashboardDashboardPagesProfileModalRoute
  ArtisanDashboardDashboardPagesScheduleRoute: typeof ArtisanDashboardDashboardPagesScheduleRoute
  ArtisanAuthForgotPasswordIndexRoute: typeof ArtisanAuthForgotPasswordIndexRoute
  ArtisanAuthLoginIndexRoute: typeof ArtisanAuthLoginIndexRoute
  ClientAuthRegisterIndexRoute: typeof ClientAuthRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtisanDashboardIndexRoute: ArtisanDashboardIndexRoute,
  ArtisanAuthRegisterArtisantRoute: ArtisanAuthRegisterArtisantRoute,
  ArtisanAuthRegisterClientRoute: ArtisanAuthRegisterClientRoute,
  ArtisanAuthRegisterVerificationCodeRoute:
    ArtisanAuthRegisterVerificationCodeRoute,
  ArtisanDashboardDashBoardComponentDashBoardMapRoute:
    ArtisanDashboardDashBoardComponentDashBoardMapRoute,
  ArtisanDashboardDashBoardComponentDashboarFeaturesRoute:
    ArtisanDashboardDashBoardComponentDashboarFeaturesRoute,
  ArtisanDashboardDashBoardComponentDashboardMainPageRoute:
    ArtisanDashboardDashBoardComponentDashboardMainPageRoute,
  ArtisanDashboardDashBoardComponentFindProAllCitiesRoute:
    ArtisanDashboardDashBoardComponentFindProAllCitiesRoute,
  ArtisanDashboardDashBoardComponentFindProAllDistancesRoute:
    ArtisanDashboardDashBoardComponentFindProAllDistancesRoute,
  ArtisanDashboardDashBoardComponentFindProAllKindsRoute:
    ArtisanDashboardDashBoardComponentFindProAllKindsRoute,
  ArtisanDashboardDashBoardComponentFindProAllStatusRoute:
    ArtisanDashboardDashBoardComponentFindProAllStatusRoute,
  ArtisanDashboardDashBoardComponentFindProProfileDetailRoute:
    ArtisanDashboardDashBoardComponentFindProProfileDetailRoute,
  ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute:
    ArtisanDashboardDashBoardComponentFindProProfileOverviewRoute,
  ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute:
    ArtisanDashboardDashBoardComponentFindProProfileSchedulesRoute,
  ArtisanDashboardDashBoardComponentFindProReviewsRoute:
    ArtisanDashboardDashBoardComponentFindProReviewsRoute,
  ArtisanDashboardDashBoardComponentNotificationRoute:
    ArtisanDashboardDashBoardComponentNotificationRoute,
  ArtisanDashboardDashBoardComponentNotificationDetailsRoute:
    ArtisanDashboardDashBoardComponentNotificationDetailsRoute,
  ArtisanDashboardDashBoardComponentProfileButtonRoute:
    ArtisanDashboardDashBoardComponentProfileButtonRoute,
  ArtisanDashboardDashBoardComponentProfileDetailsRoute:
    ArtisanDashboardDashBoardComponentProfileDetailsRoute,
  ArtisanDashboardDashBoardComponentSideBarNavRoute:
    ArtisanDashboardDashBoardComponentSideBarNavRoute,
  ArtisanDashboardDashBoardComponentStarRatingRoute:
    ArtisanDashboardDashBoardComponentStarRatingRoute,
  ArtisanDashboardDashBoardComponentViewScheduleRoute:
    ArtisanDashboardDashBoardComponentViewScheduleRoute,
  ArtisanDashboardDashBoardComponentTestsRoute:
    ArtisanDashboardDashBoardComponentTestsRoute,
  ArtisanDashboardDashboardPagesDashboardPageRoute:
    ArtisanDashboardDashboardPagesDashboardPageRoute,
  ArtisanDashboardDashboardPagesDmapRoute:
    ArtisanDashboardDashboardPagesDmapRoute,
  ArtisanDashboardDashboardPagesFavoriteRoute:
    ArtisanDashboardDashboardPagesFavoriteRoute,
  ArtisanDashboardDashboardPagesFindProHeaderRoute:
    ArtisanDashboardDashboardPagesFindProHeaderRoute,
  ArtisanDashboardDashboardPagesFindProProfileViewRoute:
    ArtisanDashboardDashboardPagesFindProProfileViewRoute,
  ArtisanDashboardDashboardPagesMessagesRoute:
    ArtisanDashboardDashboardPagesMessagesRoute,
  ArtisanDashboardDashboardPagesOrdersRoute:
    ArtisanDashboardDashboardPagesOrdersRoute,
  ArtisanDashboardDashboardPagesProfileModalRoute:
    ArtisanDashboardDashboardPagesProfileModalRoute,
  ArtisanDashboardDashboardPagesScheduleRoute:
    ArtisanDashboardDashboardPagesScheduleRoute,
  ArtisanAuthForgotPasswordIndexRoute: ArtisanAuthForgotPasswordIndexRoute,
  ArtisanAuthLoginIndexRoute: ArtisanAuthLoginIndexRoute,
  ClientAuthRegisterIndexRoute: ClientAuthRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/artisan/dashboard/",
        "/artisan/auth/register/Artisant",
        "/artisan/auth/register/Client",
        "/artisan/auth/register/VerificationCode",
        "/artisan/dashboard/DashBoardComponent/DashBoardMap",
        "/artisan/dashboard/DashBoardComponent/DashboarFeatures",
        "/artisan/dashboard/DashBoardComponent/DashboardMainPage",
        "/artisan/dashboard/DashBoardComponent/FindProAllCities",
        "/artisan/dashboard/DashBoardComponent/FindProAllDistances",
        "/artisan/dashboard/DashBoardComponent/FindProAllKinds",
        "/artisan/dashboard/DashBoardComponent/FindProAllStatus",
        "/artisan/dashboard/DashBoardComponent/FindProProfileDetail",
        "/artisan/dashboard/DashBoardComponent/FindProProfileOverview",
        "/artisan/dashboard/DashBoardComponent/FindProProfileSchedules",
        "/artisan/dashboard/DashBoardComponent/FindProReviews",
        "/artisan/dashboard/DashBoardComponent/Notification",
        "/artisan/dashboard/DashBoardComponent/NotificationDetails",
        "/artisan/dashboard/DashBoardComponent/ProfileButton",
        "/artisan/dashboard/DashBoardComponent/ProfileDetails",
        "/artisan/dashboard/DashBoardComponent/SideBarNav",
        "/artisan/dashboard/DashBoardComponent/StarRating",
        "/artisan/dashboard/DashBoardComponent/ViewSchedule",
        "/artisan/dashboard/DashBoardComponent/tests",
        "/artisan/dashboard/dashboard-pages/DashboardPage",
        "/artisan/dashboard/dashboard-pages/Dmap",
        "/artisan/dashboard/dashboard-pages/Favorite",
        "/artisan/dashboard/dashboard-pages/FindProHeader",
        "/artisan/dashboard/dashboard-pages/FindProProfileView",
        "/artisan/dashboard/dashboard-pages/Messages",
        "/artisan/dashboard/dashboard-pages/Orders",
        "/artisan/dashboard/dashboard-pages/ProfileModal",
        "/artisan/dashboard/dashboard-pages/Schedule",
        "/artisan/auth/forgot-password/",
        "/artisan/auth/login/",
        "/client/auth/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/artisan/dashboard/": {
      "filePath": "artisan/dashboard/index.tsx"
    },
    "/artisan/auth/register/Artisant": {
      "filePath": "artisan/auth/register/Artisant.tsx"
    },
    "/artisan/auth/register/Client": {
      "filePath": "artisan/auth/register/Client.tsx"
    },
    "/artisan/auth/register/VerificationCode": {
      "filePath": "artisan/auth/register/VerificationCode.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/DashBoardMap": {
      "filePath": "artisan/dashboard/DashBoardComponent/DashBoardMap.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/DashboarFeatures": {
      "filePath": "artisan/dashboard/DashBoardComponent/DashboarFeatures.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/DashboardMainPage": {
      "filePath": "artisan/dashboard/DashBoardComponent/DashboardMainPage.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProAllCities": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProAllCities.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProAllDistances": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProAllDistances.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProAllKinds": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProAllKinds.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProAllStatus": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProAllStatus.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProProfileDetail": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProProfileDetail.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProProfileOverview": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProProfileOverview.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProProfileSchedules": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProProfileSchedules.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/FindProReviews": {
      "filePath": "artisan/dashboard/DashBoardComponent/FindProReviews.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/Notification": {
      "filePath": "artisan/dashboard/DashBoardComponent/Notification.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/NotificationDetails": {
      "filePath": "artisan/dashboard/DashBoardComponent/NotificationDetails.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/ProfileButton": {
      "filePath": "artisan/dashboard/DashBoardComponent/ProfileButton.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/ProfileDetails": {
      "filePath": "artisan/dashboard/DashBoardComponent/ProfileDetails.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/SideBarNav": {
      "filePath": "artisan/dashboard/DashBoardComponent/SideBarNav.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/StarRating": {
      "filePath": "artisan/dashboard/DashBoardComponent/StarRating.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/ViewSchedule": {
      "filePath": "artisan/dashboard/DashBoardComponent/ViewSchedule.tsx"
    },
    "/artisan/dashboard/DashBoardComponent/tests": {
      "filePath": "artisan/dashboard/DashBoardComponent/tests.tsx"
    },
    "/artisan/dashboard/dashboard-pages/DashboardPage": {
      "filePath": "artisan/dashboard/dashboard-pages/DashboardPage.tsx"
    },
    "/artisan/dashboard/dashboard-pages/Dmap": {
      "filePath": "artisan/dashboard/dashboard-pages/Dmap.tsx"
    },
    "/artisan/dashboard/dashboard-pages/Favorite": {
      "filePath": "artisan/dashboard/dashboard-pages/Favorite.tsx"
    },
    "/artisan/dashboard/dashboard-pages/FindProHeader": {
      "filePath": "artisan/dashboard/dashboard-pages/FindProHeader.tsx"
    },
    "/artisan/dashboard/dashboard-pages/FindProProfileView": {
      "filePath": "artisan/dashboard/dashboard-pages/FindProProfileView.tsx"
    },
    "/artisan/dashboard/dashboard-pages/Messages": {
      "filePath": "artisan/dashboard/dashboard-pages/Messages.tsx"
    },
    "/artisan/dashboard/dashboard-pages/Orders": {
      "filePath": "artisan/dashboard/dashboard-pages/Orders.tsx"
    },
    "/artisan/dashboard/dashboard-pages/ProfileModal": {
      "filePath": "artisan/dashboard/dashboard-pages/ProfileModal.tsx"
    },
    "/artisan/dashboard/dashboard-pages/Schedule": {
      "filePath": "artisan/dashboard/dashboard-pages/Schedule.tsx"
    },
    "/artisan/auth/forgot-password/": {
      "filePath": "artisan/auth/forgot-password/index.tsx"
    },
    "/artisan/auth/login/": {
      "filePath": "artisan/auth/login/index.tsx"
    },
    "/client/auth/register/": {
      "filePath": "client/auth/register/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
